version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: seismic_data
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
